### ISSUE TITLE
bug: NewTickerPriceService.Do can't unmarshal

### ISSUE THREAD

**Issue by samonovi** [binance/binance-connector-go#17]
Hello!
When I call NewTickerPriceService.Do without symbol parameters, it returns an array of objects that cannot be parsed and returns an error.
![NewTickerPriceService_Do](https://github.com/binance/binance-connector-go/assets/82606156/94c8e254-d575-4476-b461-363112a9de9c)

**Comment by alplabin** [comment]
This issue has been fixed in version 0.8.0
