### ISSUE TITLE
StopCh can not be used to stop the websocket

### ISSUE THREAD

**Issue by SniperUsopp** [binance/binance-connector-go#18]
Seems StopCh can not be used to stop the read message, it can only silent the error handler. The function of this channel is not match its name.
<img width="782" alt="image" src="https://github.com/binance/binance-connector-go/assets/6157515/2ca50626-0b2d-42a3-8f22-1809801a2b67">

**Comment by IagoQ** [comment]
Same problem here, it seems there is no way to kill the connection on demand,  you can only wait for binance to kill the connection after some time

**Comment by alplabin** [comment]
This has been fixed in the last release: https://github.com/binance/binance-connector-go/releases/tag/v0.7.0
