### ISSUE TITLE
<APIError> code=-1121, msg=Invalid symbol.

### ISSUE THREAD

**Issue by liburdi** [binance/binance-connector-go#26]
### my code
![image](https://github.com/binance/binance-connector-go/assets/40747836/f93b3afd-caf7-445f-9e55-12006d639d26)

### err
![image](https://github.com/binance/binance-connector-go/assets/40747836/9c4f4004-9c8a-4116-bc2f-76c1a9f23e56)

### other
![image](https://github.com/binance/binance-connector-go/assets/40747836/ff848dd7-f5f9-4e35-b060-6f9264b6d4ce)
![image](https://github.com/binance/binance-connector-go/assets/40747836/f958ecd9-8c91-48d0-b9d7-bc3f6da22e48)

**Comment by aisling-2** [comment]
This is a Spot market connector, on SPOT there's no symbol `1000RATSUSDT`, hence the error.  You can confirm by using `https://api.binance.com/api/v3/exchangeInfo`.
This is unrelated with the connector's code itself.
