### ISSUE TITLE
testOrder err:<APIError> code=-1102, msg=Mandatory parameter 'signature' was not sent, was empty/null, or malformed.

### ISSUE THREAD

**Issue by liburdi** [binance/binance-connector-go#27]
![image](https://github.com/binance/binance-connector-go/assets/40747836/42890cf5-2c75-4c7d-a33c-e1cf131135a2)

**Comment by naughtybabyfirst** [comment]
You need to refer to the official documentation to see how to generate a signature and how to use it.

**Comment by alplabin** [comment]
As mentioned in the [`README`](https://github.com/binance/binance-connector-go/blob/main/README.md?plain=1#L293) file, Futures APIs are not supported by this connector. 
Therefore, you won't be able to query any futures symbols, such as 1000RATSUSDT, using this library.
