### ISSUE TITLE
NOTIONAL Order filter type not implemented!

### ISSUE THREAD

**Issue by adacaccia** [binance/binance-connector-go#29]
Hello, the followig code snippet demonstrates there's another filter tyoe, not currently implemented:

	exchangeInfo, err := anonClient.NewExchangeInfoService().Do(context.Background()).
         ...
	for _, s := range exchangeInfo.Symbols {
		if s.Symbol == symbol {
			baseAsset = s.BaseAsset
			quoteAsset = s.QuoteAsset
			// Rileviamo i valori di interesse dai filtri maledetti
			for _, f := range s.Filters {
				if f.FilterType == "LOT_SIZE" {
					minQty, err = strconv.ParseFloat(f.MinQty, 64)
					CheckErr(err)
					maxQty, err = strconv.ParseFloat(f.MaxQty, 64)
					CheckErr(err)
					stepSize, err = strconv.ParseFloat(f.StepSize, 64)
					CheckErr(err)
				}
				if f.FilterType == "MIN_NOTIONAL" {
					minNotional, err = strconv.ParseFloat(f.MinNotional, 64)
					CheckErr(err)
				}
				if f.FilterType == "NOTIONAL" {
					log.Fatalf("Encontered NOTIONAL filter: not in binance-connector-go!")
					//					notional, err = strconv.ParseFloat(f.Notional, 64)
					//					CheckErr(err)
				}
			}
			break
		}
	}

And in the log, you read at each call:

2024/04/23 15:23:19 Encontered NOTIONAL filter: not in binance-connector-go!

The commented line:

					//					notional, err = strconv.ParseFloat(f.Notional, 64)

generates a compile time error of "binance_connector.FilterType has no field 'Notional'"

So how to handle NOTIONAL filter errors on both BUY and SELL orders from time to time?
Thanks!

**Comment by adacaccia** [comment]
Here's the exact error I get:

panic: <APIError> code=-1013, msg=Filter failure: NOTIONAL

**Comment by alplabin** [comment]
Hey,
The [`NOTIONAL`](https://developers.binance.com/docs/binance-spot-api-docs/filters#notional) filter includes the following parameters:
- `minNotional`
- `applyMinToMarket`
- `maxNotional`
- `applyMaxToMarket`
- `avgPriceMins`

However, there shouldn't be any `Notional` parameters listed under the `NOTIONAL` filter type.
