### ISSUE TITLE
StopUserDataStreamService, "method": "userDataStream.stop"

### ISSUE THREAD

**Issue by hujianglong** [binance/binance-connector-go#36]
websocket_api_userdata.go 
Lines 131-133 of the websocket_api_userdata.go file，
	payload := map[string]interface{}{
		"id":     id,
		"method": "userDataStream.close",
		"params": parameters,
	}
"method": "userDataStream.close" should be："userDataStream.stop"

**Comment by alplabin** [comment]
This has been fixed in the new release: https://github.com/binance/binance-connector-go/releases/tag/v0.7.0
