### ISSUE TITLE
change go-simplejson to insane-json

### ISSUE THREAD

**Issue by mutalimov95** [binance/binance-connector-go#4]
I suggest changing [github.com/bitly/go-simplejson](https://github.com/bitly/go-simplejson) to [insane-json](https://github.com/ozontech/insane-json).

I made a small [benchmark](https://github.com/mutalimov95/go-json-bench) and found [another one](https://github.com/vitkovskii/fair-go-json-bench) from the creator of the library.

As the benchmark shows, its speed is higher, and the number of allocations is less, which is more suitable for designing high-speed applications using this API.

**Comment by 2pd** [comment]
Thank you for the feedback. When choosing the right package for this open source library for our community developers, speed is just one of the many factors that we should consider. Some others like license, adoption, repo age, etc are also important to us.  We will keep eyes on the package and will valuate if we should include it in this library.

Thank you
