### ISSUE TITLE
SubAccountTransferHistoryService response should be array

### ISSUE THREAD

**Issue by d-tovstolug** [binance/binance-connector-go#47]
Calling `SubAccountTransferHistoryService` will cause an issue `json: cannot unmarshal array into Go value of type binance_connector.SubAccountTransferHistoryResp`. 
According to [API documentation](https://binance-docs.github.io/apidocs/spot/en/#transfer-to-master-for-sub-account), this service should return `[]*SubAccountTransferHistoryService`

**Comment by alplabin** [comment]
This issue has been fixed in version 0.8.0
