### ISSUE TITLE
bookTickerService symbol not work well, symbols is good

### ISSUE THREAD

**Issue by yanglanping2022** [binance/binance-connector-go#7]
![image](https://github.com/binance/binance-connector-go/assets/134146901/1bd76c88-af9c-4ad6-8ba5-39a43a86af32)
![image](https://github.com/binance/binance-connector-go/assets/134146901/d75755fc-8cba-4a1b-8e01-f30a50273882)

**Comment by jonte-z** [comment]
Thanks for pointing this out. It's now fixed in the `0.5.0` release.
