### ISSUE TITLE
bug: TradeFeeService.DO can't unmarshal

### ISSUE THREAD

**Issue by yanglanping2022** [binance/binance-connector-go#9]
TradeFeeService.DO return array data, can't be unmarshal single obj...
![image](https://github.com/binance/binance-connector-go/assets/134146901/3e3781f1-a835-4e84-8098-edda00ef87b0)
![image](https://github.com/binance/binance-connector-go/assets/134146901/637087f2-b0e3-42a9-9e1f-07a4dec1dcd7)

**Comment by Dusty1999** [comment]
I'm trying to learn this please help and let me get my tokens

**Comment by yanglanping2022** [comment]
> I'm trying to learn this please help and let me get my tokens

what's mean tokens ? ERC20?
